{"name": "test_login_wrong_credentials", "status": "passed", "description": "Попытка авторизации с неверным логином/паролем должна возвращать 401.", "start": 1752679618108, "stop": 1752679618877, "uuid": "65efc9a0-89b9-40a9-9fa4-70c7e2e9282c", "historyId": "2a57a87a0051e72f91c0c63da8b71bf5", "testCaseId": "2a57a87a0051e72f91c0c63da8b71bf5", "fullName": "tests.test_user_login.TestUserLogin#test_login_wrong_credentials", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_user_login"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "MacBook-Pro-3.local"}, {"name": "thread", "value": "2184-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_user_login"}]}